name: 'node.js CI-CD'

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  nodejs-ci:
    runs-on: ubuntu-latest
    steps:
    - name: 1 - checkout the repository
      uses: actions/checkout@v3

    - name: 2 - Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.6.1

    - name: 3 - install dependencies
      run: npm install

    - name: 4 - build package
      run: npm run build

    - name: 5 - deploy package to npm
      if: ${{ github.ref == 'refs/heads/main' }}
      run: HUSKY=0 npm run semantic_release
